import type { SceneDefinition } from "@lyric-video-maker/plugin-base";
import { createPluginAssetUri } from "@lyric-video-maker/plugin-base";
import type { ParticleOptions } from "./types.js";

/**
 * Build scene presets. Receives defaultOptions to spread as the base.
 */
export function buildPresets(
  defaultOptions: ParticleOptions,
): SceneDefinition[] {
  function makeScene(
    id: string,
    name: string,
    description: string,
    overrides: Partial<ParticleOptions>,
  ): SceneDefinition {
    return {
      id,
      name,
      description,
      source: "plugin",
      readOnly: true,
      components: [
        {
          id: "particles-1",
          componentId: "particles.particles",
          enabled: true,
          options: { ...defaultOptions, ...overrides } as Record<string, unknown>,
        },
      ],
    };
  }

  return [
    makeScene("particles.snowfall", "Snowfall", "Gentle snowflakes drifting down with parallax depth.", {
      shape: "snowflake",
      movementPattern: "snow",
      particleCount: 80,
      speed: 20,
      speedVariation: 40,
      spawnArea: "top",
      turbulence: 40,
      colorMode: "single",
      primaryColor: "#ffffff",
      baseSize: 18,
      sizeVariation: 60,
      baseOpacity: 70,
      opacityVariation: 30,
      particleRotation: true,
      rotationSpeed: 15,
      depthEnabled: true,
      depthLayers: 3,
      depthSpeedFactor: 60,
      depthSizeFactor: 50,
      depthOpacityFactor: 40,
    }),

    makeScene("particles.starfield", "Starfield", "Twinkling stars rising with glow and depth.", {
      shape: "circle",
      movementPattern: "float-up",
      particleCount: 120,
      speed: 12,
      speedVariation: 50,
      spawnArea: "full",
      turbulence: 10,
      colorMode: "palette",
      paletteColors: "#ffffff,#cce5ff,#99ccff,#e0e0ff",
      baseSize: 4,
      sizeVariation: 60,
      baseOpacity: 80,
      opacityVariation: 40,
      particleRotation: false,
      depthEnabled: true,
      depthLayers: 4,
      depthSpeedFactor: 70,
      depthSizeFactor: 60,
      depthOpacityFactor: 50,
      glowEnabled: true,
      glowColor: "#aaccff",
      glowStrength: 60,
    }),

    makeScene("particles.confetti", "Confetti Burst", "Colorful confetti exploding outward.", {
      shape: "square",
      movementPattern: "explode",
      particleCount: 100,
      speed: 70,
      speedVariation: 40,
      spawnArea: "center",
      colorMode: "rainbow",
      baseSize: 10,
      sizeVariation: 50,
      baseOpacity: 90,
      opacityVariation: 10,
      particleRotation: true,
      rotationSpeed: 120,
    }),

    makeScene("particles.fireflies", "Fireflies", "Warm glowing particles drifting lazily.", {
      shape: "circle",
      movementPattern: "random-walk",
      particleCount: 25,
      speed: 20,
      speedVariation: 40,
      spawnArea: "full",
      turbulence: 60,
      colorMode: "palette",
      paletteColors: "#ffdd44,#ffaa22,#ffee88,#ffcc00",
      baseSize: 8,
      sizeVariation: 40,
      baseOpacity: 70,
      opacityVariation: 40,
      particleRotation: false,
      glowEnabled: true,
      glowColor: "#ffdd44",
      glowStrength: 80,
    }),

    makeScene("particles.rising-hearts", "Rising Hearts", "Hearts floating upward in pink and red.", {
      shape: "heart",
      movementPattern: "float-up",
      particleCount: 40,
      speed: 25,
      speedVariation: 30,
      spawnArea: "bottom",
      turbulence: 30,
      colorMode: "gradient-blend",
      primaryColor: "#ff4466",
      secondaryColor: "#ff88aa",
      baseSize: 22,
      sizeVariation: 50,
      baseOpacity: 80,
      opacityVariation: 20,
      particleRotation: true,
      rotationSpeed: 20,
    }),

    makeScene("particles.rain", "Rain", "Fast raindrops falling.", {
      shape: "circle",
      movementPattern: "rain",
      particleCount: 150,
      speed: 80,
      speedVariation: 30,
      spawnArea: "top",
      colorMode: "palette",
      paletteColors: "#88bbdd,#aaccee,#6699bb,#77aacc",
      baseSize: 3,
      sizeVariation: 30,
      baseOpacity: 60,
      opacityVariation: 30,
      particleRotation: false,
      trailEnabled: true,
      trailLength: 4,
      trailOpacityDecay: 40,
    }),

    makeScene("particles.bubbles", "Bubbles", "Translucent rings floating upward.", {
      shape: "ring",
      movementPattern: "float-up",
      particleCount: 35,
      speed: 15,
      speedVariation: 40,
      spawnArea: "bottom",
      turbulence: 25,
      colorMode: "palette",
      paletteColors: "#88ddff,#aaeeff,#66ccee,#bbddff,#ccbbff",
      baseSize: 25,
      sizeVariation: 70,
      baseOpacity: 50,
      opacityVariation: 30,
      particleRotation: false,
    }),

    makeScene("particles.galaxy-swirl", "Galaxy Swirl", "Sparkles swirling in a cosmic vortex.", {
      shape: "sparkle",
      movementPattern: "swirl",
      particleCount: 80,
      speed: 25,
      speedVariation: 30,
      spawnArea: "full",
      swirlRadius: 45,
      colorMode: "palette",
      paletteColors: "#bb88ff,#8866ff,#ffffff,#6644cc,#aabbff",
      baseSize: 10,
      sizeVariation: 50,
      baseOpacity: 75,
      opacityVariation: 30,
      particleRotation: true,
      rotationSpeed: 40,
      depthEnabled: true,
      depthLayers: 3,
      depthSpeedFactor: 50,
      depthSizeFactor: 40,
      depthOpacityFactor: 30,
      glowEnabled: true,
      glowColor: "#9966ff",
      glowStrength: 50,
    }),

    // Lofi+ — extends the built-in Lofi scene with warm floating particles
    {
      id: "particles.lofi-plus",
      name: "Lofi+",
      description:
        "The cozy lofi scene enhanced with warm glowing firefly particles drifting through the room.",
      source: "plugin" as const,
      readOnly: true,
      components: [
        {
          id: "background-image-1",
          componentId: "image",
          enabled: true,
          options: {
            source: createPluginAssetUri("scene-registry", "assets/lofi-background.png"),
            fitMode: "cover",
          },
        },
        {
          id: "background-color-1",
          componentId: "background-color",
          enabled: true,
          options: {
            mode: "gradient",
            direction: "0deg",
            topColor: "#1a0f0a",
            topOpacity: 25,
            bottomColor: "#1a0f0a",
            bottomOpacity: 65,
          },
        },
        {
          id: "particles-1",
          componentId: "particles.particles",
          enabled: true,
          options: {
            ...defaultOptions,
            shape: "circle",
            movementPattern: "random-walk",
            particleCount: 20,
            speed: 15,
            speedVariation: 40,
            spawnArea: "full",
            turbulence: 50,
            colorMode: "palette",
            paletteColors: "#ffb347,#ffdd88,#e8825c,#ffcc66",
            baseSize: 6,
            sizeVariation: 40,
            baseOpacity: 50,
            opacityVariation: 30,
            particleRotation: false,
            glowEnabled: true,
            glowColor: "#ffb347",
            glowStrength: 70,
          } as Record<string, unknown>,
        },
        {
          id: "equalizer-1",
          componentId: "equalizer",
          enabled: true,
          options: {
            y: 80,
            height: 20,
            layoutMode: "mirrored",
            barCount: 24,
            cornerRadius: 999,
            minBarScale: 8,
            maxBarScale: 80,
            colorMode: "gradient",
            primaryColor: "#ffb347",
            secondaryColor: "#e8825c",
            opacity: 40,
            smoothing: 55,
            attackMs: 80,
            releaseMs: 400,
            sensitivity: 1.0,
            glowEnabled: true,
            glowColor: "#ffb347",
            glowStrength: 25,
            shadowEnabled: false,
          },
        },
        {
          id: "divider-1",
          componentId: "shape",
          enabled: true,
          options: {
            shapeType: "line",
            x: 5,
            y: 80,
            width: 90,
            height: 1,
            fillEnabled: false,
            strokeEnabled: true,
            strokeColor: "#fff5e6",
            strokeWidth: 1,
            strokeOpacity: 15,
          },
        },
        {
          id: "lyrics-by-line-1",
          componentId: "lyrics-by-line",
          enabled: true,
          options: {
            height: 78,
            lyricColor: "#fff5e6",
            lyricPosition: "bottom",
            lyricSize: 64,
            shadowEnabled: true,
            shadowColor: "#1a0f0a",
            shadowIntensity: 70,
          },
        },
        {
          id: "static-text-1",
          componentId: "static-text",
          enabled: true,
          options: {
            text: "now playing",
            y: 2,
            height: 6,
            x: 2,
            width: 30,
            fontSize: 16,
            fontWeight: 300,
            color: "#aa9080",
            textAlign: "left",
            textCase: "lowercase",
          },
        },
      ],
    },
  ];
}
